/* cgtrmd.cuh - device RIPEMD-160 over a fixed 32-byte message.
 *
 * GENERATED by genrmd.ps1 - do not hand-edit the round list.
 *
 * Why generated: the message index and the rotate amount of every round have
 * to reach the compiler as literals. Read them out of a table at run time and
 * `x[table[j]]` becomes a dynamically indexed array, which nvcc is forced to
 * place in local memory - 160 local loads per digest, several times the cost
 * of the arithmetic they feed. Spelled out, x[] lives in registers and each
 * rotate folds into a single funnel-shift instruction.
 *
 * The input is always the 32-byte SHA-256 digest, so there is exactly one
 * 64-byte block and the padding is a compile-time constant too.
 */
#ifndef CGTRMD_CUH
#define CGTRMD_CUH

__device__ __forceinline__ unsigned int cgtRotL(unsigned int x, int n) {
  return (x << n) | (x >> (32 - n));
}

#define CGT_RF1(x,y,z) ((x) ^ (y) ^ (z))
#define CGT_RF2(x,y,z) (((x) & (y)) | (~(x) & (z)))
#define CGT_RF3(x,y,z) (((x) | ~(y)) ^ (z))
#define CGT_RF4(x,y,z) (((x) & (z)) | ((y) & ~(z)))
#define CGT_RF5(x,y,z) ((x) ^ ((y) | ~(z)))

/* a += f(b,c,d) + x + k;  a = rotl(a,s) + e;  c = rotl(c,10) */
#define CGT_RSTEP(f,a,b,c,d,e,xv,k,s)      \
  a += f(b,c,d) + (xv) + (k);              \
  a = cgtRotL(a, s) + e;                   \
  c = cgtRotL(c, 10);

/* sha[] arrives as 8 big-endian words; RIPEMD reads little-endian words. */
__device__ __forceinline__ void cgtRmd160(const unsigned int sha[8],
                                          unsigned int out[5]) {
  unsigned int x[16];
  #pragma unroll
  for (int i = 0; i < 8; i++) {
    unsigned int v = sha[i];
    x[i] = ((v & 0xFFu) << 24) | ((v & 0xFF00u) << 8) |
           ((v >> 8) & 0xFF00u) | (v >> 24);
  }
  x[ 8] = 0x00000080u;   /* the 0x80 pad, immediately after 32 bytes */
  x[ 9] = 0; x[10] = 0; x[11] = 0; x[12] = 0; x[13] = 0;
  x[14] = 32 * 8;        /* bit length, low word */
  x[15] = 0;

  unsigned int la = 0x67452301u, lb = 0xEFCDAB89u, lc = 0x98BADCFEu,
               ld = 0x10325476u, le = 0xC3D2E1F0u;
  unsigned int ra = la, rb = lb, rc = lc, rd = ld, re = le;

  /* ---- left line ---- */
  CGT_RSTEP(CGT_RF1, la, lb, lc, ld, le, x[ 0], 0x00000000u, 11);
  CGT_RSTEP(CGT_RF1, le, la, lb, lc, ld, x[ 1], 0x00000000u, 14);
  CGT_RSTEP(CGT_RF1, ld, le, la, lb, lc, x[ 2], 0x00000000u, 15);
  CGT_RSTEP(CGT_RF1, lc, ld, le, la, lb, x[ 3], 0x00000000u, 12);
  CGT_RSTEP(CGT_RF1, lb, lc, ld, le, la, x[ 4], 0x00000000u,  5);
  CGT_RSTEP(CGT_RF1, la, lb, lc, ld, le, x[ 5], 0x00000000u,  8);
  CGT_RSTEP(CGT_RF1, le, la, lb, lc, ld, x[ 6], 0x00000000u,  7);
  CGT_RSTEP(CGT_RF1, ld, le, la, lb, lc, x[ 7], 0x00000000u,  9);
  CGT_RSTEP(CGT_RF1, lc, ld, le, la, lb, x[ 8], 0x00000000u, 11);
  CGT_RSTEP(CGT_RF1, lb, lc, ld, le, la, x[ 9], 0x00000000u, 13);
  CGT_RSTEP(CGT_RF1, la, lb, lc, ld, le, x[10], 0x00000000u, 14);
  CGT_RSTEP(CGT_RF1, le, la, lb, lc, ld, x[11], 0x00000000u, 15);
  CGT_RSTEP(CGT_RF1, ld, le, la, lb, lc, x[12], 0x00000000u,  6);
  CGT_RSTEP(CGT_RF1, lc, ld, le, la, lb, x[13], 0x00000000u,  7);
  CGT_RSTEP(CGT_RF1, lb, lc, ld, le, la, x[14], 0x00000000u,  9);
  CGT_RSTEP(CGT_RF1, la, lb, lc, ld, le, x[15], 0x00000000u,  8);

  CGT_RSTEP(CGT_RF2, le, la, lb, lc, ld, x[ 7], 0x5A827999u,  7);
  CGT_RSTEP(CGT_RF2, ld, le, la, lb, lc, x[ 4], 0x5A827999u,  6);
  CGT_RSTEP(CGT_RF2, lc, ld, le, la, lb, x[13], 0x5A827999u,  8);
  CGT_RSTEP(CGT_RF2, lb, lc, ld, le, la, x[ 1], 0x5A827999u, 13);
  CGT_RSTEP(CGT_RF2, la, lb, lc, ld, le, x[10], 0x5A827999u, 11);
  CGT_RSTEP(CGT_RF2, le, la, lb, lc, ld, x[ 6], 0x5A827999u,  9);
  CGT_RSTEP(CGT_RF2, ld, le, la, lb, lc, x[15], 0x5A827999u,  7);
  CGT_RSTEP(CGT_RF2, lc, ld, le, la, lb, x[ 3], 0x5A827999u, 15);
  CGT_RSTEP(CGT_RF2, lb, lc, ld, le, la, x[12], 0x5A827999u,  7);
  CGT_RSTEP(CGT_RF2, la, lb, lc, ld, le, x[ 0], 0x5A827999u, 12);
  CGT_RSTEP(CGT_RF2, le, la, lb, lc, ld, x[ 9], 0x5A827999u, 15);
  CGT_RSTEP(CGT_RF2, ld, le, la, lb, lc, x[ 5], 0x5A827999u,  9);
  CGT_RSTEP(CGT_RF2, lc, ld, le, la, lb, x[ 2], 0x5A827999u, 11);
  CGT_RSTEP(CGT_RF2, lb, lc, ld, le, la, x[14], 0x5A827999u,  7);
  CGT_RSTEP(CGT_RF2, la, lb, lc, ld, le, x[11], 0x5A827999u, 13);
  CGT_RSTEP(CGT_RF2, le, la, lb, lc, ld, x[ 8], 0x5A827999u, 12);

  CGT_RSTEP(CGT_RF3, ld, le, la, lb, lc, x[ 3], 0x6ED9EBA1u, 11);
  CGT_RSTEP(CGT_RF3, lc, ld, le, la, lb, x[10], 0x6ED9EBA1u, 13);
  CGT_RSTEP(CGT_RF3, lb, lc, ld, le, la, x[14], 0x6ED9EBA1u,  6);
  CGT_RSTEP(CGT_RF3, la, lb, lc, ld, le, x[ 4], 0x6ED9EBA1u,  7);
  CGT_RSTEP(CGT_RF3, le, la, lb, lc, ld, x[ 9], 0x6ED9EBA1u, 14);
  CGT_RSTEP(CGT_RF3, ld, le, la, lb, lc, x[15], 0x6ED9EBA1u,  9);
  CGT_RSTEP(CGT_RF3, lc, ld, le, la, lb, x[ 8], 0x6ED9EBA1u, 13);
  CGT_RSTEP(CGT_RF3, lb, lc, ld, le, la, x[ 1], 0x6ED9EBA1u, 15);
  CGT_RSTEP(CGT_RF3, la, lb, lc, ld, le, x[ 2], 0x6ED9EBA1u, 14);
  CGT_RSTEP(CGT_RF3, le, la, lb, lc, ld, x[ 7], 0x6ED9EBA1u,  8);
  CGT_RSTEP(CGT_RF3, ld, le, la, lb, lc, x[ 0], 0x6ED9EBA1u, 13);
  CGT_RSTEP(CGT_RF3, lc, ld, le, la, lb, x[ 6], 0x6ED9EBA1u,  6);
  CGT_RSTEP(CGT_RF3, lb, lc, ld, le, la, x[13], 0x6ED9EBA1u,  5);
  CGT_RSTEP(CGT_RF3, la, lb, lc, ld, le, x[11], 0x6ED9EBA1u, 12);
  CGT_RSTEP(CGT_RF3, le, la, lb, lc, ld, x[ 5], 0x6ED9EBA1u,  7);
  CGT_RSTEP(CGT_RF3, ld, le, la, lb, lc, x[12], 0x6ED9EBA1u,  5);

  CGT_RSTEP(CGT_RF4, lc, ld, le, la, lb, x[ 1], 0x8F1BBCDCu, 11);
  CGT_RSTEP(CGT_RF4, lb, lc, ld, le, la, x[ 9], 0x8F1BBCDCu, 12);
  CGT_RSTEP(CGT_RF4, la, lb, lc, ld, le, x[11], 0x8F1BBCDCu, 14);
  CGT_RSTEP(CGT_RF4, le, la, lb, lc, ld, x[10], 0x8F1BBCDCu, 15);
  CGT_RSTEP(CGT_RF4, ld, le, la, lb, lc, x[ 0], 0x8F1BBCDCu, 14);
  CGT_RSTEP(CGT_RF4, lc, ld, le, la, lb, x[ 8], 0x8F1BBCDCu, 15);
  CGT_RSTEP(CGT_RF4, lb, lc, ld, le, la, x[12], 0x8F1BBCDCu,  9);
  CGT_RSTEP(CGT_RF4, la, lb, lc, ld, le, x[ 4], 0x8F1BBCDCu,  8);
  CGT_RSTEP(CGT_RF4, le, la, lb, lc, ld, x[13], 0x8F1BBCDCu,  9);
  CGT_RSTEP(CGT_RF4, ld, le, la, lb, lc, x[ 3], 0x8F1BBCDCu, 14);
  CGT_RSTEP(CGT_RF4, lc, ld, le, la, lb, x[ 7], 0x8F1BBCDCu,  5);
  CGT_RSTEP(CGT_RF4, lb, lc, ld, le, la, x[15], 0x8F1BBCDCu,  6);
  CGT_RSTEP(CGT_RF4, la, lb, lc, ld, le, x[14], 0x8F1BBCDCu,  8);
  CGT_RSTEP(CGT_RF4, le, la, lb, lc, ld, x[ 5], 0x8F1BBCDCu,  6);
  CGT_RSTEP(CGT_RF4, ld, le, la, lb, lc, x[ 6], 0x8F1BBCDCu,  5);
  CGT_RSTEP(CGT_RF4, lc, ld, le, la, lb, x[ 2], 0x8F1BBCDCu, 12);

  CGT_RSTEP(CGT_RF5, lb, lc, ld, le, la, x[ 4], 0xA953FD4Eu,  9);
  CGT_RSTEP(CGT_RF5, la, lb, lc, ld, le, x[ 0], 0xA953FD4Eu, 15);
  CGT_RSTEP(CGT_RF5, le, la, lb, lc, ld, x[ 5], 0xA953FD4Eu,  5);
  CGT_RSTEP(CGT_RF5, ld, le, la, lb, lc, x[ 9], 0xA953FD4Eu, 11);
  CGT_RSTEP(CGT_RF5, lc, ld, le, la, lb, x[ 7], 0xA953FD4Eu,  6);
  CGT_RSTEP(CGT_RF5, lb, lc, ld, le, la, x[12], 0xA953FD4Eu,  8);
  CGT_RSTEP(CGT_RF5, la, lb, lc, ld, le, x[ 2], 0xA953FD4Eu, 13);
  CGT_RSTEP(CGT_RF5, le, la, lb, lc, ld, x[10], 0xA953FD4Eu, 12);
  CGT_RSTEP(CGT_RF5, ld, le, la, lb, lc, x[14], 0xA953FD4Eu,  5);
  CGT_RSTEP(CGT_RF5, lc, ld, le, la, lb, x[ 1], 0xA953FD4Eu, 12);
  CGT_RSTEP(CGT_RF5, lb, lc, ld, le, la, x[ 3], 0xA953FD4Eu, 13);
  CGT_RSTEP(CGT_RF5, la, lb, lc, ld, le, x[ 8], 0xA953FD4Eu, 14);
  CGT_RSTEP(CGT_RF5, le, la, lb, lc, ld, x[11], 0xA953FD4Eu, 11);
  CGT_RSTEP(CGT_RF5, ld, le, la, lb, lc, x[ 6], 0xA953FD4Eu,  8);
  CGT_RSTEP(CGT_RF5, lc, ld, le, la, lb, x[15], 0xA953FD4Eu,  5);
  CGT_RSTEP(CGT_RF5, lb, lc, ld, le, la, x[13], 0xA953FD4Eu,  6);

  /* ---- right line ---- */
  CGT_RSTEP(CGT_RF5, ra, rb, rc, rd, re, x[ 5], 0x50A28BE6u,  8);
  CGT_RSTEP(CGT_RF5, re, ra, rb, rc, rd, x[14], 0x50A28BE6u,  9);
  CGT_RSTEP(CGT_RF5, rd, re, ra, rb, rc, x[ 7], 0x50A28BE6u,  9);
  CGT_RSTEP(CGT_RF5, rc, rd, re, ra, rb, x[ 0], 0x50A28BE6u, 11);
  CGT_RSTEP(CGT_RF5, rb, rc, rd, re, ra, x[ 9], 0x50A28BE6u, 13);
  CGT_RSTEP(CGT_RF5, ra, rb, rc, rd, re, x[ 2], 0x50A28BE6u, 15);
  CGT_RSTEP(CGT_RF5, re, ra, rb, rc, rd, x[11], 0x50A28BE6u, 15);
  CGT_RSTEP(CGT_RF5, rd, re, ra, rb, rc, x[ 4], 0x50A28BE6u,  5);
  CGT_RSTEP(CGT_RF5, rc, rd, re, ra, rb, x[13], 0x50A28BE6u,  7);
  CGT_RSTEP(CGT_RF5, rb, rc, rd, re, ra, x[ 6], 0x50A28BE6u,  7);
  CGT_RSTEP(CGT_RF5, ra, rb, rc, rd, re, x[15], 0x50A28BE6u,  8);
  CGT_RSTEP(CGT_RF5, re, ra, rb, rc, rd, x[ 8], 0x50A28BE6u, 11);
  CGT_RSTEP(CGT_RF5, rd, re, ra, rb, rc, x[ 1], 0x50A28BE6u, 14);
  CGT_RSTEP(CGT_RF5, rc, rd, re, ra, rb, x[10], 0x50A28BE6u, 14);
  CGT_RSTEP(CGT_RF5, rb, rc, rd, re, ra, x[ 3], 0x50A28BE6u, 12);
  CGT_RSTEP(CGT_RF5, ra, rb, rc, rd, re, x[12], 0x50A28BE6u,  6);

  CGT_RSTEP(CGT_RF4, re, ra, rb, rc, rd, x[ 6], 0x5C4DD124u,  9);
  CGT_RSTEP(CGT_RF4, rd, re, ra, rb, rc, x[11], 0x5C4DD124u, 13);
  CGT_RSTEP(CGT_RF4, rc, rd, re, ra, rb, x[ 3], 0x5C4DD124u, 15);
  CGT_RSTEP(CGT_RF4, rb, rc, rd, re, ra, x[ 7], 0x5C4DD124u,  7);
  CGT_RSTEP(CGT_RF4, ra, rb, rc, rd, re, x[ 0], 0x5C4DD124u, 12);
  CGT_RSTEP(CGT_RF4, re, ra, rb, rc, rd, x[13], 0x5C4DD124u,  8);
  CGT_RSTEP(CGT_RF4, rd, re, ra, rb, rc, x[ 5], 0x5C4DD124u,  9);
  CGT_RSTEP(CGT_RF4, rc, rd, re, ra, rb, x[10], 0x5C4DD124u, 11);
  CGT_RSTEP(CGT_RF4, rb, rc, rd, re, ra, x[14], 0x5C4DD124u,  7);
  CGT_RSTEP(CGT_RF4, ra, rb, rc, rd, re, x[15], 0x5C4DD124u,  7);
  CGT_RSTEP(CGT_RF4, re, ra, rb, rc, rd, x[ 8], 0x5C4DD124u, 12);
  CGT_RSTEP(CGT_RF4, rd, re, ra, rb, rc, x[12], 0x5C4DD124u,  7);
  CGT_RSTEP(CGT_RF4, rc, rd, re, ra, rb, x[ 4], 0x5C4DD124u,  6);
  CGT_RSTEP(CGT_RF4, rb, rc, rd, re, ra, x[ 9], 0x5C4DD124u, 15);
  CGT_RSTEP(CGT_RF4, ra, rb, rc, rd, re, x[ 1], 0x5C4DD124u, 13);
  CGT_RSTEP(CGT_RF4, re, ra, rb, rc, rd, x[ 2], 0x5C4DD124u, 11);

  CGT_RSTEP(CGT_RF3, rd, re, ra, rb, rc, x[15], 0x6D703EF3u,  9);
  CGT_RSTEP(CGT_RF3, rc, rd, re, ra, rb, x[ 5], 0x6D703EF3u,  7);
  CGT_RSTEP(CGT_RF3, rb, rc, rd, re, ra, x[ 1], 0x6D703EF3u, 15);
  CGT_RSTEP(CGT_RF3, ra, rb, rc, rd, re, x[ 3], 0x6D703EF3u, 11);
  CGT_RSTEP(CGT_RF3, re, ra, rb, rc, rd, x[ 7], 0x6D703EF3u,  8);
  CGT_RSTEP(CGT_RF3, rd, re, ra, rb, rc, x[14], 0x6D703EF3u,  6);
  CGT_RSTEP(CGT_RF3, rc, rd, re, ra, rb, x[ 6], 0x6D703EF3u,  6);
  CGT_RSTEP(CGT_RF3, rb, rc, rd, re, ra, x[ 9], 0x6D703EF3u, 14);
  CGT_RSTEP(CGT_RF3, ra, rb, rc, rd, re, x[11], 0x6D703EF3u, 12);
  CGT_RSTEP(CGT_RF3, re, ra, rb, rc, rd, x[ 8], 0x6D703EF3u, 13);
  CGT_RSTEP(CGT_RF3, rd, re, ra, rb, rc, x[12], 0x6D703EF3u,  5);
  CGT_RSTEP(CGT_RF3, rc, rd, re, ra, rb, x[ 2], 0x6D703EF3u, 14);
  CGT_RSTEP(CGT_RF3, rb, rc, rd, re, ra, x[10], 0x6D703EF3u, 13);
  CGT_RSTEP(CGT_RF3, ra, rb, rc, rd, re, x[ 0], 0x6D703EF3u, 13);
  CGT_RSTEP(CGT_RF3, re, ra, rb, rc, rd, x[ 4], 0x6D703EF3u,  7);
  CGT_RSTEP(CGT_RF3, rd, re, ra, rb, rc, x[13], 0x6D703EF3u,  5);

  CGT_RSTEP(CGT_RF2, rc, rd, re, ra, rb, x[ 8], 0x7A6D76E9u, 15);
  CGT_RSTEP(CGT_RF2, rb, rc, rd, re, ra, x[ 6], 0x7A6D76E9u,  5);
  CGT_RSTEP(CGT_RF2, ra, rb, rc, rd, re, x[ 4], 0x7A6D76E9u,  8);
  CGT_RSTEP(CGT_RF2, re, ra, rb, rc, rd, x[ 1], 0x7A6D76E9u, 11);
  CGT_RSTEP(CGT_RF2, rd, re, ra, rb, rc, x[ 3], 0x7A6D76E9u, 14);
  CGT_RSTEP(CGT_RF2, rc, rd, re, ra, rb, x[11], 0x7A6D76E9u, 14);
  CGT_RSTEP(CGT_RF2, rb, rc, rd, re, ra, x[15], 0x7A6D76E9u,  6);
  CGT_RSTEP(CGT_RF2, ra, rb, rc, rd, re, x[ 0], 0x7A6D76E9u, 14);
  CGT_RSTEP(CGT_RF2, re, ra, rb, rc, rd, x[ 5], 0x7A6D76E9u,  6);
  CGT_RSTEP(CGT_RF2, rd, re, ra, rb, rc, x[12], 0x7A6D76E9u,  9);
  CGT_RSTEP(CGT_RF2, rc, rd, re, ra, rb, x[ 2], 0x7A6D76E9u, 12);
  CGT_RSTEP(CGT_RF2, rb, rc, rd, re, ra, x[13], 0x7A6D76E9u,  9);
  CGT_RSTEP(CGT_RF2, ra, rb, rc, rd, re, x[ 9], 0x7A6D76E9u, 12);
  CGT_RSTEP(CGT_RF2, re, ra, rb, rc, rd, x[ 7], 0x7A6D76E9u,  5);
  CGT_RSTEP(CGT_RF2, rd, re, ra, rb, rc, x[10], 0x7A6D76E9u, 15);
  CGT_RSTEP(CGT_RF2, rc, rd, re, ra, rb, x[14], 0x7A6D76E9u,  8);

  CGT_RSTEP(CGT_RF1, rb, rc, rd, re, ra, x[12], 0x00000000u,  8);
  CGT_RSTEP(CGT_RF1, ra, rb, rc, rd, re, x[15], 0x00000000u,  5);
  CGT_RSTEP(CGT_RF1, re, ra, rb, rc, rd, x[10], 0x00000000u, 12);
  CGT_RSTEP(CGT_RF1, rd, re, ra, rb, rc, x[ 4], 0x00000000u,  9);
  CGT_RSTEP(CGT_RF1, rc, rd, re, ra, rb, x[ 1], 0x00000000u, 12);
  CGT_RSTEP(CGT_RF1, rb, rc, rd, re, ra, x[ 5], 0x00000000u,  5);
  CGT_RSTEP(CGT_RF1, ra, rb, rc, rd, re, x[ 8], 0x00000000u, 14);
  CGT_RSTEP(CGT_RF1, re, ra, rb, rc, rd, x[ 7], 0x00000000u,  6);
  CGT_RSTEP(CGT_RF1, rd, re, ra, rb, rc, x[ 6], 0x00000000u,  8);
  CGT_RSTEP(CGT_RF1, rc, rd, re, ra, rb, x[ 2], 0x00000000u, 13);
  CGT_RSTEP(CGT_RF1, rb, rc, rd, re, ra, x[13], 0x00000000u,  6);
  CGT_RSTEP(CGT_RF1, ra, rb, rc, rd, re, x[14], 0x00000000u,  5);
  CGT_RSTEP(CGT_RF1, re, ra, rb, rc, rd, x[ 0], 0x00000000u, 15);
  CGT_RSTEP(CGT_RF1, rd, re, ra, rb, rc, x[ 3], 0x00000000u, 13);
  CGT_RSTEP(CGT_RF1, rc, rd, re, ra, rb, x[ 9], 0x00000000u, 11);
  CGT_RSTEP(CGT_RF1, rb, rc, rd, re, ra, x[11], 0x00000000u, 11);

  /* The two lines are combined with a one-word rotation of the state. */
  unsigned int t = 0xEFCDAB89u + lc + rd;
  out[1] = 0x98BADCFEu + ld + re;
  out[2] = 0x10325476u + le + ra;
  out[3] = 0xC3D2E1F0u + la + rb;
  out[4] = 0x67452301u + lb + rc;
  out[0] = t;
}

#endif /* CGTRMD_CUH */
